/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPatientWindow.java
 *
 * Created on Apr 8, 2010, 12:48:15 PM
 */

package main;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dan
 */
public class AddPatientWindow extends javax.swing.JFrame {

    /** Creates new form AddPatientWindow */
    public AddPatientWindow(SchedulerGUI schedulerGUI) {
        initComponents();
        this.schedulerGUI = schedulerGUI;
    }

    private boolean toggle_patientFirstNameTextBox  = false;
    private boolean toggle_patientLastNameTextBox   = false;
    private boolean toggle_patientAgeTextBox        = false;

    private String  patientFirstName;
    private String  patientLastName;
    private int     patientAge;
    private String  patientSex = "";
    private String  patientComplaint;
    private int     patientAcuity;
    private SchedulerGUI schedulerGUI;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientAgeTextBox = new javax.swing.JTextField();
        patientAcuityComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientLastNameTextBox = new javax.swing.JTextField();
        patientFirstNameTextBox = new javax.swing.JTextField();
        patientSexComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        addPatientButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        complaintComboBox = new javax.swing.JComboBox();

        setTitle("Add New Patient");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        jLabel4.setText("Age:");

        jLabel3.setText("Sex:");

        patientAgeTextBox.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){checkLength("patientAgeTextBox");}
            public void removeUpdate(DocumentEvent e){checkLength("patientAgeTextBox");}
            public void insertUpdate(DocumentEvent e){checkLength("patientAgeTextBox");}
        });

        patientAcuityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel5.setText("Acuity:");

        jLabel2.setText("First Name:");

        patientLastNameTextBox.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){checkLength("patientLastNameTextBox");}
            public void removeUpdate(DocumentEvent e){checkLength("patientLastNameTextBox");}
            public void insertUpdate(DocumentEvent e){checkLength("patientLastNameTextBox");}
        });

        patientFirstNameTextBox.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e){checkLength("patientFirstNameTextBox");}
            public void removeUpdate(DocumentEvent e){checkLength("patientFirstNameTextBox");}
            public void insertUpdate(DocumentEvent e){checkLength("patientFirstNameTextBox");}
        });

        patientSexComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel7.setText("Last Name:");

        this.addPatientButton.setEnabled(false);
        addPatientButton.setText("Add");
        addPatientButton.setEnabled(false);
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Complaint:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPatientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(complaintComboBox, 0, 216, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(patientSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientAcuityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientAgeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(patientFirstNameTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(patientLastNameTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientFirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(patientAgeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(patientAcuityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complaintComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        patientFirstName = patientFirstNameTextBox.getText();
        patientLastName = patientLastNameTextBox.getText();
        System.out.println(patientAgeTextBox.getText());
        System.out.println(patientAgeTextBox.getText().isEmpty());
        String patientAgeString = patientAgeTextBox.getText();
        patientAge = Integer.parseInt(patientAgeString);
//        System.out.println(pSCB.toString());
        patientSex = patientSexComboBox.getSelectedItem().toString();
        /** @FIX patientComplaint to be read from a combo box or list*/
        patientComplaint = "";

        try {
            /**
             * @TODO: send parameters to ParameterProcessor to be added to DB and OPR lists
             */
            schedulerGUI.getParameterProcessor().addPatient();
        } catch (SQLException ex) {
            Logger.getLogger(AddPatientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        schedulerGUI.addPatient();
        this.setVisible(false);

        patientFirstNameTextBox.setText("");
        patientLastNameTextBox.setText("");
        patientAgeTextBox.setText("");
        validate();

}//GEN-LAST:event_addPatientButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    public int getPatientAge() {
        return patientAge;
    }

    public void setPatientAge(int patientAge) {
        this.patientAge = patientAge;
    }

    public String getPatientFirstName() {
        return patientFirstName;
    }

    public void setPatientFirstName(String patientFirstName) {
        this.patientFirstName = patientFirstName;
    }

    public String getPatientLastName() {
        return patientLastName;
    }

    public void setPatientLastName(String patientLastName) {
        this.patientLastName = patientLastName;
    }

    public String getPatientSex() {
        return patientSex;
    }

    public void setPatientSex(String patientSex) {
        this.patientSex = patientSex;
    }

    public int getPatientAcuity() {
        return patientAcuity;
    }

    public String getPatientComplaint() {
        return patientComplaint;
    }



    private void checkLength(String componentName){
        if(componentName.equalsIgnoreCase("patientFirstNameTextBox")){
            if(patientFirstNameTextBox.getDocument().getLength() > 0){
                toggle_patientFirstNameTextBox = true;
            }
            else{
                toggle_patientFirstNameTextBox = false;
            }
            checkTogglesForPatientAddButtonEnabling();
        }
        else if(componentName.equalsIgnoreCase("patientLastNameTextBox")){
            if(patientLastNameTextBox.getDocument().getLength() > 0){
                toggle_patientLastNameTextBox = true;
            }
            else{
                toggle_patientLastNameTextBox = false;
            }
            checkTogglesForPatientAddButtonEnabling();
        }
        else if(componentName.equalsIgnoreCase("patientAgeTextBox")){
            if(patientAgeTextBox.getDocument().getLength() > 0){
                toggle_patientAgeTextBox = true;
            }
            else{
                toggle_patientAgeTextBox = false;
            }
            checkTogglesForPatientAddButtonEnabling();
        }
    }

    private void checkTogglesForPatientAddButtonEnabling(){
        if(
                toggle_patientFirstNameTextBox == true &&
                toggle_patientLastNameTextBox == true &&
                toggle_patientAgeTextBox == true
                ){
            addPatientButton.setEnabled(true);
        }
        else{
            addPatientButton.setEnabled(false);
        }
    }

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddPatientWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox complaintComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox patientAcuityComboBox;
    private javax.swing.JTextField patientAgeTextBox;
    private javax.swing.JTextField patientFirstNameTextBox;
    private javax.swing.JTextField patientLastNameTextBox;
    private javax.swing.JComboBox patientSexComboBox;
    // End of variables declaration//GEN-END:variables

}
