/*
 * DeleteOperationDialog.java
 *
 * Created on March 24, 2010, 1:42 PM
 */

package main;

/**
 *
 * @author  Dan
 */
public class DeleteOperationDialog extends javax.swing.JDialog {

    private boolean confirmChangeWithReschedule = false;
    private boolean confirmChangeWithoutReschedule = false;
    
    
    /** Creates new form DeleteOperationDialog */
    public DeleteOperationDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        withRescheduleButton = new javax.swing.JButton();
        withoutRescheduleButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("WARNING: You are about to alter the current schedule.  This action cannot be undone.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/warning.png"))); // NOI18N

        jLabel3.setText("Proceed...");

        withRescheduleButton.setText("WITH reschedule");
        withRescheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withRescheduleButtonActionPerformed(evt);
            }
        });

        withoutRescheduleButton.setText("WITHOUT reschedule");
        withoutRescheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withoutRescheduleButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(withRescheduleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(withoutRescheduleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(withoutRescheduleButton)
                    .addComponent(withRescheduleButton)
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void withRescheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withRescheduleButtonActionPerformed
    setConfirmChangeWithReschedule(true);
    this.setVisible(false);
}//GEN-LAST:event_withRescheduleButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
 
    setConfirmChangeWithReschedule(false);
    setConfirmChangeWithoutReschedule(false);
    this.setVisible(false);
    
//    this.notifyAll();
}//GEN-LAST:event_cancelButtonActionPerformed

private void withoutRescheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withoutRescheduleButtonActionPerformed

    setConfirmChangeWithoutReschedule(true);
    this.setVisible(false);
    
}//GEN-LAST:event_withoutRescheduleButtonActionPerformed

    public boolean isConfirmChangeWithReschedule() {
        return confirmChangeWithReschedule;
    }

    public void setConfirmChangeWithReschedule(boolean confirmChangeWithReschedule) {
        this.confirmChangeWithReschedule = confirmChangeWithReschedule;
    }

    public boolean isConfirmChangeWithoutReschedule() {
        return confirmChangeWithoutReschedule;
    }

    public void setConfirmChangeWithoutReschedule(boolean confirmChangeWithoutReschedule) {
        this.confirmChangeWithoutReschedule = confirmChangeWithoutReschedule;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteOperationDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton withRescheduleButton;
    private javax.swing.JButton withoutRescheduleButton;
    // End of variables declaration//GEN-END:variables

}
