/*
 * schedulerGUI.java
 *
 * Created on February 2, 2010, 6:28 PM
 */

package main;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Dan
 */
public class SchedulerGUI extends javax.swing.JFrame {

    private ParameterProcessor parameterProcessor;
    private Scheduler scheduler;
//    Scheduler scheduler = Main.scheduler;
    AddPatientWindow addPatientWindow = new AddPatientWindow(this);
    private TestCaseParameterWindow testCaseParameterWindow = new TestCaseParameterWindow(this, true);
    private ParameterDialog parameterDialog = new ParameterDialog(this, true);

    private boolean testCaseEntered = false;
    private int testCaseHour;
    private int testCaseMinute;

    private GanttJFrame ganttJFrame;
    static int instances=0;


    /** Creates new form schedulerGUI */
    public SchedulerGUI() throws SQLException {
        
        initComponents();
        parameterProcessor = new ParameterProcessor(this);
        scheduler = new Scheduler(parameterProcessor);
//        instances++;
//        System.out.println("instances of SchedulerGUI: "+instances);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataViewTable = new javax.swing.JTable();
        deleteFromPatientListButton = new javax.swing.JButton();
        editPatientListButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        generateNewScheduleButton = new javax.swing.JButton();
        showCurrentScheduleGanttButton = new javax.swing.JButton();
        addPatientButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("Item");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emory University Hospital OSCAR  v20100503");
        setLocationByPlatform(true);

        dataViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patient Name", "Sex", "Age", "Acuity", "Complaints", "Arrival Time", "Next Operation", "Estimated LOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataViewTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataViewTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataViewTable);
        dataViewTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        dataViewTable.getColumnModel().getColumn(0).setResizable(false);
        dataViewTable.getColumnModel().getColumn(0).setPreferredWidth(1);
        dataViewTable.getColumnModel().getColumn(1).setResizable(false);
        dataViewTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        dataViewTable.getColumnModel().getColumn(2).setResizable(false);
        dataViewTable.getColumnModel().getColumn(2).setPreferredWidth(1);
        dataViewTable.getColumnModel().getColumn(3).setResizable(false);
        dataViewTable.getColumnModel().getColumn(3).setPreferredWidth(1);
        dataViewTable.getColumnModel().getColumn(4).setResizable(false);
        dataViewTable.getColumnModel().getColumn(4).setPreferredWidth(1);
        dataViewTable.getColumnModel().getColumn(5).setResizable(false);
        dataViewTable.getColumnModel().getColumn(6).setResizable(false);
        dataViewTable.getColumnModel().getColumn(7).setResizable(false);
        dataViewTable.getColumnModel().getColumn(8).setResizable(false);

        deleteFromPatientListButton.setText("Delete");
        deleteFromPatientListButton.setEnabled(false);
        deleteFromPatientListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFromPatientListButtonActionPerformed(evt);
            }
        });

        editPatientListButton.setText("Edit");
        editPatientListButton.setEnabled(false);
        editPatientListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatientListButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Gantt Chart:");

        generateNewScheduleButton.setText("Generate New Schedule");
        generateNewScheduleButton.setEnabled(false);
        generateNewScheduleButton.setName("generateNewScheduleButton"); // NOI18N
        generateNewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateNewScheduleButton(evt);
            }
        });

        showCurrentScheduleGanttButton.setText("Show Current");
        showCurrentScheduleGanttButton.setEnabled(false);
        showCurrentScheduleGanttButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCurrentScheduleGanttButtonActionPerformed(evt);
            }
        });

        addPatientButton.setText("Add Patient");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        jMenu2.setText("Edit");

        jMenuItem3.setText("Parameters");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenu4.setEnabled(false);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                        .addComponent(generateNewScheduleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showCurrentScheduleGanttButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPatientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPatientListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteFromPatientListButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteFromPatientListButton)
                    .addComponent(editPatientListButton)
                    .addComponent(addPatientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(showCurrentScheduleGanttButton)
                    .addComponent(generateNewScheduleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void generateNewScheduleButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateNewScheduleButton
//    GregorianCalendar startRunTime = new GregorianCalendar();


    ganttJFrame = new GanttJFrame();

    SchedulerSwingWorker sSW = new SchedulerSwingWorker(scheduler, ganttJFrame);
    sSW.execute();

//    GregorianCalendar endRunTime = new GregorianCalendar();
//    long milliDiff = endRunTime.getTimeInMillis() - startRunTime.getTimeInMillis();
//    double secDiff = milliDiff * 0.001;
//    DecimalFormat round2 = new DecimalFormat("#.##");
//    double secDiffRounded = Double.valueOf(round2.format(secDiff));
//    System.out.println("Runtime: " + secDiffRounded + " seconds");

//GEN-LAST:event_generateNewScheduleButton
    ganttButtonClicked++;
        
}                                    

private void editPatientListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientListButtonActionPerformed
    System.out.println("edit button pressed");
}//GEN-LAST:event_editPatientListButtonActionPerformed

private void showCurrentScheduleGanttButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCurrentScheduleGanttButtonActionPerformed
    ganttJFrame.setVisible(true);
}//GEN-LAST:event_showCurrentScheduleGanttButtonActionPerformed

private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
    addPatientWindow.setVisible(true);
//    addPatient();
    editPatientListButton.setEnabled(false);
        deleteFromPatientListButton.setEnabled(false);
}//GEN-LAST:event_addPatientButtonActionPerformed

private void deleteFromPatientListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFromPatientListButtonActionPerformed
    DefaultTableModel tableModel = (DefaultTableModel) dataViewTable.getModel();
    if (dataViewTable.getSelectedRow() != -1){
        tableModel.removeRow(dataViewTable.getSelectedRow());
        editPatientListButton.setEnabled(false);
        deleteFromPatientListButton.setEnabled(false);
    }
    /**
     * @TODO add SQL REMOVE query here
     * @TODO add remove calls to O,P,R Lists
     */

    
}//GEN-LAST:event_deleteFromPatientListButtonActionPerformed

private void dataViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataViewTableMouseClicked
    if (dataViewTable.getSelectedRow() != -1){
        editPatientListButton.setEnabled(true);
        deleteFromPatientListButton.setEnabled(true);
    }
}//GEN-LAST:event_dataViewTableMouseClicked

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    parameterDialog.setVisible(true);
}//GEN-LAST:event_jMenuItem3ActionPerformed


public void printTestCaseOutput(){
    OperationList tempOL = parameterProcessor.getOperationList();
//            OperationList.sortByID(tempOL);
                System.out.println("|  O   |  P  |Acu| R |s_date |s_time |e_date |e_time |");
                System.out.println("+----------------------------------------------------+");
            for(Object opOb : tempOL){
                Operation op = (Operation) opOb;
                Patient patient = parameterProcessor.getPatientList().getByID(op.getPatientID());

                //OperationID string
                String opID_s = String.valueOf(op.getID());
                    if(opID_s.length() == 1){
                        opID_s = "000".concat(opID_s);
                    }else if(opID_s.length() == 2){
                        opID_s = "00".concat(opID_s);
                    }else if(opID_s.length() == 3){
                        opID_s = "0".concat(opID_s);
                    }

                //PatientID string
                String patID_s = String.valueOf(op.getPatientID());
                    if(patID_s.length() == 1){
                        patID_s = "00".concat(patID_s);
                    }else if(patID_s.length() == 2){
                        patID_s = "0".concat(patID_s);
                    }

                //ResourceID string
                String resID_s = String.valueOf(op.getResourceID());

                //Start time string
//                System.out.println("startDate: "+op.getStartDate());
                String startDate_s = String.valueOf(op.getStartDate());
                    if(startDate_s.length() == 1){
                        startDate_s = "0".concat(startDate_s);
                    }
                String startHour_s = String.valueOf(op.getStartHour());
                    if(startHour_s.length() == 1){
                        startHour_s = "0".concat(startHour_s);
                    }
                String startMin_s = String.valueOf(op.getStartMinute());
                    if(startMin_s.length() == 1){
                        startMin_s = "0".concat(startMin_s);
                    }

                //End time string
                String endDate_s = String.valueOf(op.getEndDate());
//                System.out.println("enddate: "+op.getEndDate());
                    if(endDate_s.length() == 1){
                        endDate_s = "0".concat(endDate_s);
                    }
                String endHour_s = String.valueOf(op.getEndHour());
                    if(endHour_s.length() == 1){
                        endHour_s = "0".concat(endHour_s);
                    }
                String endMin_s = String.valueOf(op.getEndMinute());
                    if(endMin_s.length() == 1){
                        endMin_s = "0".concat(endMin_s);
                    }

                System.out.println("| "+opID_s+" | "+patID_s+" | "+patient.getAcuity()+" | "+resID_s+" | 0"+(op.getStartMonth()+1)+"-"+startDate_s+" | "+startHour_s+":"+startMin_s+" | 04-"+endDate_s+" | "+endHour_s+":"+endMin_s);
            }
            System.out.println("+----------------------------------------------------+");
            System.out.print("\n\r");


            /**
             * PRINT LOS's for each patient
             */
            PatientList tempPL = parameterProcessor.getPatientList();
            PatientList.sortByID(tempPL);
//            System.out.println("Patient LOS");
//            System.out.println("----------------------------------------");
            for(Object patObj : tempPL){
                Patient patient = (Patient) patObj;
                long lengthOfStay = scheduler.calculatePatientLOS(patient);
                System.out.println("Patient "+patient.getID()+": "+lengthOfStay);
            }
//            System.out.print("\n\r");
}


    public JTable getDataViewTable() {
        return dataViewTable;
    }

    public void setDataViewTable(DefaultTableModel tableModel) {
        dataViewTable.setModel(tableModel);
    }

    public void addPatient(){
        /**
         * Post the info to the MainGUI table
         **/
         System.out.println("SchedulerGUI.addPatient()");
//         DefaultTableModel tableModel = new DefaultTableModel();
        DefaultTableModel tableModel = (DefaultTableModel) dataViewTable.getModel();

        Vector rowVector = new Vector();

        rowVector.addElement("");
        rowVector.addElement(addPatientWindow.getPatientLastName()+", "+addPatientWindow.getPatientFirstName());
        rowVector.addElement(addPatientWindow.getPatientSex());
        rowVector.addElement(addPatientWindow.getPatientAge());
        rowVector.addElement(addPatientWindow.getPatientAcuity());
        rowVector.addElement("");
        rowVector.addElement("");
        rowVector.addElement("");
        rowVector.addElement("");

        String patientName = addPatientWindow.getPatientLastName()+", "+addPatientWindow.getPatientFirstName();
        int patientAge = addPatientWindow.getPatientAge();
        int patientAcuity = addPatientWindow.getPatientAcuity();
        if(addPatientWindow.getPatientSex().equalsIgnoreCase("male")){
            int patientSex = 1;
        }else{
            int patientSex = 0;
        }
        /**
         * @TODO: Fix patientComplaint to map complaint to integer ID for RRPT database query
         */
        int patientComplaint = 0;

//        parameterProcessor.getPatientList().add(new Patient(patientName,0,patientAcuity,patientAge,patientSex,patientComplaint,1,0,0,1,0,0,0,1,0,0));

        tableModel.addRow(rowVector);
        
        tableModel.fireTableDataChanged();
        dataViewTable.setModel(tableModel);

        this.validate();

        /**
         * @TODO add INSERT query to add new patient
         * @TODO add insert for operationList, PatientList, ResourceList
         */

    }

    public boolean isTestCaseEntered() {
        return testCaseEntered;
    }

    public void setTestCaseEntered(boolean testCaseEntered) {
        this.testCaseEntered = testCaseEntered;
    }

    public int getTestCaseHour() {
        return testCaseHour;
    }

    public void setTestCaseHour(int testCaseHour) {
        this.testCaseHour = testCaseHour;
    }

    public int getTestCaseMinute() {
        return testCaseMinute;
    }

    public void setTestCaseMinute(int testCaseMinute) {
        this.testCaseMinute = testCaseMinute;
    }

    public ParameterProcessor getParameterProcessor() {
        return parameterProcessor;
    }



//public void run() {
//        try {
//            new SchedulerGUI().setVisible(true);
//        } catch (SQLException ex) {
//            Logger.getLogger(SchedulerGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SchedulerGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SchedulerGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    private int ganttButtonClicked = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JTable dataViewTable;
    private javax.swing.JButton deleteFromPatientListButton;
    private javax.swing.JButton editPatientListButton;
    private javax.swing.JButton generateNewScheduleButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton showCurrentScheduleGanttButton;
    // End of variables declaration//GEN-END:variables

    

}
