/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestCaseParameterWindow.java
 *
 * Created on Apr 13, 2010, 11:29:38 PM
 */

package main;

/**
 *
 * @author Dan
 */
public class TestCaseParameterWindow extends javax.swing.JDialog {

    private int hour    =   -1;
    private int minute  =   -1;
    private int patientID  =-1;
    private int testCase = -1;

    private boolean goToTimePressed=    false;
    private boolean addPatientPressed=  false;
    private boolean runTestCaseButtonPressed = false;

    /** Creates new form TestCaseParameterWindow */
    public TestCaseParameterWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hourTextBox = new javax.swing.JTextField();
        patientIDTextBox = new javax.swing.JTextField();
        minuteTextBox = new javax.swing.JTextField();
        goToTimeButton = new javax.swing.JButton();
        addPatientButton = new javax.swing.JButton();
        testCaseTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        runTestCaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Patient ID:");

        jLabel2.setText("Hour of Day:");

        jLabel3.setText("Minute:");

        goToTimeButton.setText("Go to Time");
        goToTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToTimeButtonActionPerformed(evt);
            }
        });

        addPatientButton.setText("Add Patient at Time");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Test Case:");

        runTestCaseButton.setText("Run Test Case");
        runTestCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runTestCaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(patientIDTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hourTextBox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minuteTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(testCaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(runTestCaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goToTimeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPatientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPatientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hourTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(minuteTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goToTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(testCaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runTestCaseButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToTimeButtonActionPerformed
        hour = Integer.parseInt(hourTextBox.getText());
        minute = Integer.parseInt(minuteTextBox.getText());

        addPatientPressed = false;
        runTestCaseButtonPressed = false;
        goToTimePressed = true;

        this.setVisible(false);

        hourTextBox.setText("");
        minuteTextBox.setText("");
    }//GEN-LAST:event_goToTimeButtonActionPerformed

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        patientID = Integer.parseInt(patientIDTextBox.getText());
//        hour = Integer.parseInt(hourTextBox.getText());
//        minute = Integer.parseInt(minuteTextBox.getText());
        
        addPatientPressed = true;
        goToTimePressed = false;

        this.setVisible(false);

//        patientIDTextBox.setText("");
//        hourTextBox.setText("");
//        minuteTextBox.setText("");
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void runTestCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runTestCaseButtonActionPerformed
        testCase = Integer.parseInt(testCaseTextBox.getText());

        addPatientPressed = false;
        runTestCaseButtonPressed = true;
        goToTimePressed = false;

        this.setVisible(false);
        testCaseTextBox.setText("");
    }//GEN-LAST:event_runTestCaseButtonActionPerformed

    public int getHour() {
        return hour;
    }

    public void setHour(int hour) {
        this.hour = hour;
    }

    public int getMinute() {
        return minute;
    }

    public void setMinute(int minute) {
        this.minute = minute;
    }

    public int getPatientID() {
        return patientID;
    }

    public void setPatientID(int patientID) {
        this.patientID = patientID;
    }

    public boolean isAddPatientPressed() {
        return addPatientPressed;
    }

    public void setAddPatientPressed(boolean addPatientPressed) {
        this.addPatientPressed = addPatientPressed;
    }

    public boolean isGoToTimePressed() {
        return goToTimePressed;
    }

    public void setGoToTimePressed(boolean goToTimePressed) {
        this.goToTimePressed = goToTimePressed;
    }

    public boolean isRunTestCaseButtonPressed() {
        return runTestCaseButtonPressed;
    }

    public void setRunTestCaseButtonPressed(boolean runTestCaseButtonPressed) {
        this.runTestCaseButtonPressed = runTestCaseButtonPressed;
    }

    public int getTestCase() {
        return testCase;
    }

    public void setTestCase(int testCase) {
        this.testCase = testCase;
    }



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestCaseParameterWindow dialog = new TestCaseParameterWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton goToTimeButton;
    private javax.swing.JTextField hourTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField minuteTextBox;
    private javax.swing.JTextField patientIDTextBox;
    private javax.swing.JButton runTestCaseButton;
    private javax.swing.JTextField testCaseTextBox;
    // End of variables declaration//GEN-END:variables

}
